name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    
    strategy:
      matrix:
        xcode: ['15.0.1']
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Build
      run: |
        xcodebuild build \
          -project "SomaFM miniplayer.xcodeproj" \
          -scheme "SomaFM miniplayer" \
          -destination "platform=macOS" \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
          
    - name: Run Tests
      run: |
        xcodebuild test \
          -project "SomaFM miniplayer.xcodeproj" \
          -scheme "SomaFM miniplayer" \
          -destination "platform=macOS" \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
          
  analyze:
    name: Static Analysis
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
      
    - name: Analyze
      run: |
        xcodebuild analyze \
          -project "SomaFM miniplayer.xcodeproj" \
          -scheme "SomaFM miniplayer" \
          -destination "platform=macOS" \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO