name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
      
    - name: Build for Release
      run: |
        xcodebuild archive \
          -project "SomaFM miniplayer.xcodeproj" \
          -scheme "SomaFM miniplayer" \
          -archivePath "$PWD/build/SomaFM miniplayer.xcarchive" \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=NO
          
    - name: Export App
      run: |
        xcodebuild -exportArchive \
          -archivePath "$PWD/build/SomaFM miniplayer.xcarchive" \
          -exportPath "$PWD/build" \
          -exportOptionsPlist "$PWD/.github/workflows/ExportOptions.plist"
          
    - name: Create DMG
      run: |
        mkdir -p build/dmg
        cp -R "build/SomaFM miniplayer.app" build/dmg/
        hdiutil create -volname "SomaFM miniplayer" -srcfolder build/dmg -ov -format UDZO "build/SomaFM-miniplayer-${{ github.ref_name }}.dmg"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/SomaFM-miniplayer-${{ github.ref_name }}.dmg
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}